version: '3'

services:

  api:
    restart: unless-stopped
    build:
      context: ./api
    expose:
      - 3000
    env_file:
      - ./api/.env
    environment:
      DATABASE_URL: file:./db.sqlite
      PRISMA_CLIENT_OUTPUT: "/app/.output/server/node_modules/.prisma/client"
    command: >
      sh -c "
      cd /app &&
      npx prisma db push &&
      npm run start"

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
    expose:
      - 3000

  reverse-proxy:
    restart: unless-stopped
    image: nginx:stable
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
